### ISSUE TITLE
Problem with multiple modules

### ISSUE THREAD

**Issue by shumkov** [marcoslin/angularAMD#13]
When i use several modules for my application and declare its before run `angularAMD.bootstrap` they doesn't support lazy injecting components (`register` property) .

Simple example:

```
define('app', [ 'angular', 'angularAMD', 'app.module' ], function(angular, angularAMD) {
  var app = angular.module('app', [ 'app.module' ]);

  angularAMD.bootstrap(app);

  return app;
});

define('app.module', [ 'angular' ], function() {
   var module = angular.module('app.module', [ ]);

   // .. Configurate route with using angularAMD.route({ controllerURL : 'ModuleController'  })

   return module;
});

define('ModuleController', [ 'app.module' ], function(module) {
   module.register.controller(...);
   // register is undefined
});
```

How can i mixin `register` to `module` without bootstraping it?

**Comment by akhare22sandeep** [comment]
marcoslin, i am also facing the same issue. my Application was in single module everything was working fine. But when i modularized it by creating different modules by features all contollers are services started throwing error. Basically non of the new modules have "Register" method and directly putting .controller is failing with error Argument 'VehiclesController' is not a function, got undefined. 

BTW , as per UI -router , we should setup state in respective modules rather than core module. Please advise. 
https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-ui-router-from-multiple-modules

**Comment by yogeshlonkar** [comment]
@akhare22sandeep  I have created small repository [angular-lazy-register](https://github.com/yogeshlonkar/angular-lazy-register) for simple function which facilitates multi modules  to load controllers, services lazy way which solved problem for me. You can try it, It might help you.

**Comment by marcoslin** [comment]
@akhare22sandeep the documentation link you provided apply for normal angular js modules.  What you need to do in this case is to create a normal angular JS module as per document link you provided, then load it using `ngload`.  See documentation here:

https://github.com/marcoslin/angularAMD#3rd-party-angularjs-modules

Try to open a new issue if problem persist and post some sample code so I can better help you.  Sorry for the long respond time.
